[tool.poetry]
name = "django-static-templates"
version = "1.0.0"
description = "Use Django's template engine to generate static files at deployment time."
authors = ["Brian Kohan <bckohan@gmail.com>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/bckohan/django-static-templates"
homepage = "https://django-static-templates.readthedocs.io"
keywords = ["django", "static", "templates"]
classifiers = [
    "Environment :: Console",
    "Framework :: Django",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
Django = "^3.0"
Jinja2 = "^2.11.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-django = "^4.1.0"
Sphinx = "^3.3.1"
sphinx-rtd-theme = "^0.5.0"
mypy = "^0.790"
isort = "^5.6.4"
doc8 = "^0.8.1"
darglint = "^1.5.7"
pytest-cov = "^2.11.1"
pylint = "^2.6.0"
sphinx-argparse = "^0.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
