name: test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version:
          - 'Django~=2.2.0'
          - 'Django~=3.0.0'
          - 'Django~=3.1.0'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
    - name: Install Release Dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install
        poetry run pip install -U "${{ matrix.django-version }}"
    - name: Run Unit Tests
      run: |
        poetry run pytest
        poetry run pylint static_templates
        poetry run mypy static_templates
        poetry run doc8 -q docs
        poetry check
        poetry run pip check
        poetry run safety check --full-report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml